### ISSUE TITLE
[Bug] Mark as done not syncing from vikunja

### ISSUE THREAD

**Issue by 3m0W33D** [Heiss/obsidian-vikunja-plugin#10]
Manual Sync
I have an issue when marking a tasks completed on vikunja, and performing a sync, it priorities obsidian, causing the task to be unset on vikunja. Not sure if this is the intended behaviour.

Sync on startup
I have read that if no changes are done to the markdown, the updated tasks are pulled from vikunja. However, this does not work for me.
When this option is enabled and obsidian is started, vikunja fails to recognize the daily notes plugin and gives me this error.
![image](https://github.com/user-attachments/assets/27543ec2-86f5-47fe-9f5f-3f4375d08538)
I have to manually perform a dependency check for the plugin to start working again.

Essentially, I am unable to pull any tasks marked as completed from vikunja unless I delete my whole list of tasks, and perform a sync again.

P.S Thanks for taking the time and effort to make this plugin it is really useful for my use case and I am really glad that someone has developed this. Cheers!

**Comment by Heiss** [comment]
Hey. thank you for your issue.

The second one can be replicated on my side. Sync on startup is related on the dependency check you mentioned. So if there is a plugin not loaded, the sync aborts. So this should be the reason, why sync on startup does not work as expected.

The first one is not intended... Currently the updated timestamp for obsidian is pretty silly and is equal with the containing file modified date. So if anything changes the file (e.g. your sync program) or its content, all tasks within this file will be updated via the plugin to vikunja, regardless if one task was updated or a line of text in this file or any program touches the file without any changes. In a future release i want to implement a real caching solution, which tracks updated date on per-tasks.

**Comment by 3m0W33D** [comment]
Hey thanks for answer, good to hear that it wasn't just me misunderstanding how the plugin worked or simply me going crazy cause my setup isn't working [😂](https://emojipedia.org/face-with-tears-of-joy). Glad to hear that your are continuing to develop this.

**Comment by Heiss** [comment]
hey,

the new version 1.0.12 implements the cache. I tested it in my use case, but more testing is highly appreciated. 
Sadly, there is a bug with labels. It creates the same tag SOMETIMES multiple times. This bug exists already in previous versions. So this is not new, but i thought i fixed it twice... But i hope, i got it fixed in the next version in a way, that it will be fixed by itself on a sync.

Feel free to comment and reopen this issue. Otherwise i close it for now.
