### ISSUE TITLE
Unclear how to configure dataview

### ISSUE THREAD

**Issue by VerbTheNoun95** [Heiss/obsidian-vikunja-plugin#17]
Thanks for putting this plugin together, I'm very excited to get it working.

I can't seem to get an initial sync going, though. After installing both the dataview plugin and then this one, and after enabling the daily notes core plugin, I'm getting an error in the console that says "No views found. Please configure the plugin before using it." which is stopping me from syncing.

I have confirmed that my vikunja API key is working and that the plugin can connect/authenticate. I've set the default project in the plugin to a Vikunja project that definitely has tasks. I've also created some dummy dataviews to confirm that the dataview plugin is working.

Is there something specific I need to do to configure a dataview for this plugin (e.g. in the daily note file)? Or is there some other command in the vikunja plugin command palette that should set up the necessary dataviews?

Any help is appreciated!

Versions:
 - Obsidian version: v1.6.7
 - Dataview v0.5.67
 - Vikunja Sync v1.0.19

**Comment by Heiss** [comment]
Hey,
the error message appears, if it does not found any kanban board for your selected project. Please check settings, select a default project and (if more than one kanban view added) select one (the selection is hidden, if only one was found).

I agree, the setup process is not user friendly. I will add a point to readme ASAP.

**Comment by VerbTheNoun95** [comment]
Thanks for the quick response. The default project did have a kanban board set up and populated with tasks in different buckets. I was actually able to get the sync working by manually editing the `$OBSIDIAN_DIRECTORY/.obsidian/plugins/vikunja-sync/data.json` file and changing `"availableViews": []` to `"availableViews": [0]`. For some reason, that wasn't getting set via the plugin settings inside obsidian. As you said, that selection is hidden if there's one kanban view in the project, so it was silently failing on me.

Not sure why that was the case, otherwise I'd provide more useful troubleshooting information.

**Comment by Heiss** [comment]
I think i know where it comes from. There is a flaw in settings, which circumvent this. I add this issue to my todo list #13 .
